const ClinicalSummary = require('../models/ClinicalSummary');
const ClinicalSession = require('../models/ClinicalSession');
const ClinicalHistory = require('../models/ClinicalHistory');
const MedicalDocument = require('../models/MedicalDocument');
const User = require('../models/User');
const AyushHistory = require('../models/AyushHistory');
const HealthRecord = require('../models/HealthRecord');
const geminiSummaryService = require('./geminiSummaryService');

class ClinicalSummaryService {
  /**
   * Main function to collect all patient data, detect conflicts, call Gemini summarizer, and persist ClinicalSummary
   */
  async generateClinicalSummary({ patientId, clinicalSessionId, summaryLanguage = 'en' }) {
    // 1. Fetch Patient Profile
    const patient = await User.findById(patientId);

    // 2. Fetch Clinical Session & Touch/Voice History
    const session = await ClinicalSession.findOne({ sessionId: clinicalSessionId });
    const history = await ClinicalHistory.findOne({ sessionId: clinicalSessionId });

    // 3. Fetch Medical Documents from Step 3
    const documents = await MedicalDocument.find({
      patientId,
      processingStatus: { $in: ['processed', 'needs_review', 'uploaded'] }
    });

    // 4. Fetch AYUSH History
    const ayush = await AyushHistory.findOne({ clinicalSessionId });

    // 5. Fetch Health Records
    const healthRecords = await HealthRecord.find({ patientId });

    // 6. Assemble Multi-Source Inputs
    const consolidatedInput = this.consolidatePatientData({
      patient,
      session,
      history,
      documents,
      ayush,
      healthRecords,
      language: summaryLanguage
    });

    // 7. Execute Gemini Summary Engine
    const summaryResult = await geminiSummaryService.generateClinicalSummary(consolidatedInput);

    // 8. Save or Update ClinicalSummary Record in Database
    let summaryDoc = await ClinicalSummary.findOne({ clinicalSessionId });

    if (!summaryDoc) {
      summaryDoc = new ClinicalSummary({
        patientId,
        clinicalSessionId,
        version: 1
      });
    } else if (summaryDoc.physicianVerified) {
      // Preserve prior version in history before updating
      summaryDoc.versionHistory.push({
        version: summaryDoc.version,
        summaryData: summaryDoc.generatedSummary,
        modifiedBy: 'system_regeneration',
        modifiedAt: new Date(),
        changeReason: 'Regenerated by patient/system after physician verification'
      });
      summaryDoc.version += 1;
      summaryDoc.status = 'patient_review';
    }

    // Populate Fields
    summaryDoc.patientHealthId = patient?.healthId || session?.patientHealthId;
    summaryDoc.patientName = patient ? `${patient.firstName} ${patient.lastName}`.trim() : session?.patientName;
    summaryDoc.patientAge = patient?.age || null;
    summaryDoc.patientGender = patient?.gender || null;

    summaryDoc.chiefComplaint = summaryResult.chiefComplaint || consolidatedInput.chiefComplaint;
    summaryDoc.historyOfPresentIllness = summaryResult.historyOfPresentIllness || consolidatedInput.historyOfPresentIllness;
    summaryDoc.pastMedicalHistory = summaryResult.pastMedicalHistory || consolidatedInput.pastMedicalHistory;
    summaryDoc.pastSurgicalHistory = summaryResult.pastSurgicalHistory || consolidatedInput.pastSurgicalHistory;
    summaryDoc.currentMedications = summaryResult.currentMedications || consolidatedInput.currentMedications;
    summaryDoc.drugAllergies = summaryResult.drugAllergies || consolidatedInput.drugAllergies;
    summaryDoc.noKnownAllergiesReported = consolidatedInput.noKnownAllergiesReported;
    summaryDoc.allergiesAssessed = consolidatedInput.allergiesAssessed;
    summaryDoc.familyHistory = summaryResult.familyHistory || consolidatedInput.familyHistory;
    summaryDoc.personalHistory = summaryResult.personalHistory || consolidatedInput.personalHistory;
    summaryDoc.reviewOfSystems = summaryResult.reviewOfSystems || consolidatedInput.reviewOfSystems;
    summaryDoc.priorInvestigations = summaryResult.previousInvestigations || consolidatedInput.priorInvestigations;
    summaryDoc.documentFindings = consolidatedInput.documentFindings;
    summaryDoc.ayushHistory = ayush ? ayush.toObject() : summaryResult.ayushHistory;
    summaryDoc.redFlags = consolidatedInput.redFlags;
    summaryDoc.missingInformation = summaryResult.missingInformation || consolidatedInput.missingInformation;
    summaryDoc.conflicts = consolidatedInput.conflicts;
    summaryDoc.generatedSummary = summaryResult;
    summaryDoc.clinicalSummaryText = summaryResult.clinicalSummaryText || '';
    summaryDoc.summaryLanguage = summaryLanguage;
    summaryDoc.status = summaryDoc.status === 'physician_verified' ? 'patient_review' : summaryDoc.status || 'draft';

    await summaryDoc.save();
    return summaryDoc;
  }

  /**
   * Consolidates multi-source data and tags provenance + detects conflicts & missing fields
   */
  consolidatePatientData({ patient, session, history, documents, ayush, healthRecords, language }) {
    const rawAnswers = session?.answers ? Object.fromEntries(session.answers) : {};
    const redFlags = session?.redFlags || history?.redFlags || [];
    const conflicts = [];
    const missingInfo = [];

    // Patient Reported Medications
    const patientMeds = [];
    if (history?.currentMedications && Array.isArray(history.currentMedications)) {
      history.currentMedications.forEach((m) => {
        patientMeds.push({
          name: typeof m === 'string' ? m : m.name || m.medicineName,
          dose: m.dose || '',
          frequency: m.frequency || '',
          route: m.route || '',
          duration: m.duration || '',
          source: 'patient_reported',
          isPatientReported: true,
          isDocumentExtracted: false
        });
      });
    }

    // Document Extracted Medications
    const docMeds = [];
    const priorInvestigations = [];
    const documentFindings = [];

    if (documents && Array.isArray(documents)) {
      documents.forEach((doc) => {
        const ext = doc.aiExtractedData || {};
        documentFindings.push({
          documentId: doc._id,
          documentType: doc.documentType,
          fileName: doc.originalFileName,
          summaryText: ext.documentSummary || ext.summary || `${doc.documentType} uploaded`,
          keyExtractions: ext
        });

        // Extract medications
        if (ext.medications && Array.isArray(ext.medications)) {
          ext.medications.forEach((m) => {
            docMeds.push({
              name: m.name || m.medicineName,
              dose: m.dosage || m.dose || '',
              frequency: m.frequency || '',
              route: m.route || '',
              duration: m.duration || '',
              source: 'medical_document',
              isPatientReported: false,
              isDocumentExtracted: true,
              documentId: doc._id
            });
          });
        }

        // Extract laboratory tests & abnormal findings
        if (ext.laboratoryResults && Array.isArray(ext.laboratoryResults)) {
          ext.laboratoryResults.forEach((lab) => {
            priorInvestigations.push({
              testName: lab.testName || lab.test || 'Lab Test',
              testDate: lab.testDate || doc.documentDate ? new Date(doc.documentDate).toLocaleDateString() : '',
              resultValue: lab.value || lab.result || '',
              unit: lab.unit || '',
              referenceRange: lab.referenceRange || '',
              isAbnormal: Boolean(lab.isAbnormal || lab.flag === 'HIGH' || lab.flag === 'LOW'),
              source: 'medical_document',
              documentId: doc._id
            });
          });
        }
      });
    }

    // Merge medications & detect conflicts
    const allMeds = [...patientMeds];
    docMeds.forEach((dMed) => {
      const existingIndex = allMeds.findIndex(
        (pMed) => pMed.name.toLowerCase().trim() === dMed.name.toLowerCase().trim()
      );
      if (existingIndex !== -1) {
        allMeds[existingIndex].isDocumentExtracted = true;
        allMeds[existingIndex].documentId = dMed.documentId;
        // Check for dosage/frequency conflicts
        if (dMed.dose && allMeds[existingIndex].dose && dMed.dose !== allMeds[existingIndex].dose) {
          conflicts.push({
            field: `Medication Dose: ${dMed.name}`,
            patientValue: allMeds[existingIndex].dose,
            documentValue: dMed.dose,
            notes: 'Source conflict — physician review required'
          });
        }
      } else {
        allMeds.push(dMed);
      }
    });

    // Drug Allergies handling
    let drugAllergies = [];
    let noKnownAllergiesReported = false;
    let allergiesAssessed = false;

    if (history?.drugAllergies) {
      allergiesAssessed = true;
      if (Array.isArray(history.drugAllergies) && history.drugAllergies.length > 0) {
        drugAllergies = history.drugAllergies.map((a) => ({
          allergen: typeof a === 'string' ? a : a.allergen || a.name,
          reaction: a.reaction || '',
          severity: a.severity || 'unknown',
          source: 'patient_reported'
        }));
      } else {
        noKnownAllergiesReported = true;
      }
    } else {
      missingInfo.push('Drug allergies: Not assessed');
    }

    // Missing Info audit
    if (!history?.familyHistory || (Array.isArray(history.familyHistory) && history.familyHistory.length === 0)) {
      missingInfo.push('Family history: Not provided');
    }
    if (!history?.pastSurgicalHistory || (Array.isArray(history.pastSurgicalHistory) && history.pastSurgicalHistory.length === 0)) {
      missingInfo.push('Past surgical history: Not provided');
    }

    return {
      patientId: patient?._id || session?.patientId,
      patientName: patient ? `${patient.firstName} ${patient.lastName}`.trim() : session?.patientName,
      patientAge: patient?.age || null,
      patientGender: patient?.gender || null,
      language,
      chiefComplaint: history?.chiefComplaint || { text: 'Not provided', source: 'patient_reported' },
      historyOfPresentIllness: history?.historyOfPresentIllness || { rawText: 'Not provided' },
      pastMedicalHistory: history?.pastMedicalHistory || [],
      pastSurgicalHistory: history?.pastSurgicalHistory || [],
      currentMedications: allMeds,
      drugAllergies,
      noKnownAllergiesReported,
      allergiesAssessed,
      familyHistory: history?.familyHistory || [],
      personalHistory: history?.personalHistory || { diet: 'Not provided' },
      reviewOfSystems: history?.reviewOfSystems || {},
      priorInvestigations,
      documentFindings,
      ayushHistory: ayush ? ayush.toObject() : null,
      redFlags,
      missingInformation: missingInfo,
      conflicts
    };
  }

  /**
   * Build multi-source unified medical timeline
   */
  async getMedicalTimeline(patientId) {
    const timelineItems = [];

    // 1. Patient Reported Past Medical History
    const historyRecords = await ClinicalHistory.find({ patientId });
    historyRecords.forEach((h) => {
      if (h.pastMedicalHistory && Array.isArray(h.pastMedicalHistory)) {
        h.pastMedicalHistory.forEach((item) => {
          timelineItems.push({
            id: `pmh-${h._id}-${item.value || item}`,
            category: 'Past Condition',
            title: item.value || item,
            date: h.completedAt ? new Date(h.completedAt).toISOString() : new Date().toISOString(),
            dateType: 'intake_date',
            source: 'patient_reported',
            details: item.notes || 'Reported during clinical history session'
          });
        });
      }
      if (h.pastSurgicalHistory && Array.isArray(h.pastSurgicalHistory)) {
        h.pastSurgicalHistory.forEach((item) => {
          timelineItems.push({
            id: `psh-${h._id}-${item.procedure}`,
            category: 'Surgery / Procedure',
            title: item.procedure,
            date: item.date || (h.completedAt ? new Date(h.completedAt).toISOString() : new Date().toISOString()),
            dateType: item.date ? 'procedure_date' : 'intake_date',
            source: 'patient_reported',
            details: item.details || 'Reported surgical procedure'
          });
        });
      }
    });

    // 2. Uploaded & Processed Medical Documents
    const documents = await MedicalDocument.find({ patientId });
    documents.forEach((doc) => {
      const ext = doc.aiExtractedData || {};
      const docDate = doc.documentDate || doc.uploadedAt;
      const isDocDateActual = Boolean(doc.documentDate);

      timelineItems.push({
        id: `doc-${doc._id}`,
        category: doc.documentType ? doc.documentType.toUpperCase().replace('_', ' ') : 'DOCUMENT UPLOAD',
        title: doc.originalFileName,
        date: docDate ? new Date(docDate).toISOString() : new Date().toISOString(),
        dateType: isDocDateActual ? 'medical_document_date' : 'upload_date',
        source: 'medical_document',
        documentId: doc._id,
        details: ext.documentSummary || ext.summary || `Extracted ${doc.documentType}`
      });
    });

    // Sort chronologically descending (newest first)
    timelineItems.sort((a, b) => new Date(b.date) - new Date(a.date));

    return timelineItems;
  }
}

module.exports = new ClinicalSummaryService();
